apiVersion: v1
kind: Pod
metadata:
  name: my-app-with-secret-env
spec:
  containers:
  - name: my-app-container
    image: my-image:latest
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
