apiVersion: v1
kind: Pod
metadata:
  name: my-app-with-resources
spec:
  containers:
  - name: my-app-container
    image: my-image:latest
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "0.5"
        memory: "256Mi"
