apiVersion: v1
kind: Pod
metadata:
  name: my-multicontainer-app
spec:
  containers:
  - name: frontend
    image: frontend-image:latest
    ports:
    - containerPort: 80
  - name: backend
    image: backend-image:latest
    ports:
    - containerPort: 8080
  - name: database
    image: database-image:latest
    ports:
    - containerPort: 5432
